-- MySQL Script generated by MySQL Workbench
-- Mon Jun 15 09:48:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jardinerie_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jardinerie_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jardinerie_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `jardinerie_db` ;

-- -----------------------------------------------------
-- Table `jardinerie_db`.`taxes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`taxes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `rate` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('admin', 'customer') NULL DEFAULT 'customer',
  `registration_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `gdpr_consent_key` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `recipient_first_name` VARCHAR(100) NOT NULL,
  `recipient_last_name` VARCHAR(100) NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `postal_code` VARCHAR(20) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `country` VARCHAR(100) NOT NULL DEFAULT 'France',
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_addresses_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `jardinerie_db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `icon_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`department_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_categories_departments`
    FOREIGN KEY (`department_id`)
    REFERENCES `jardinerie_db`.`departments` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`subcategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`subcategories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`category_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_subcategories_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `jardinerie_db`.`categories` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subcategory_id` INT NOT NULL,
  `tax_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price_tax_incl` DECIMAL(10,2) NOT NULL,
  `purchase_price_tax_incl` DECIMAL(10,2) NULL DEFAULT NULL,
  `stock_quantity` INT NULL DEFAULT 0,
  `main_image_url` VARCHAR(255) NULL DEFAULT NULL,
  `secondary_image_url` VARCHAR(255) NULL DEFAULT NULL,
  `is_active` TINYINT NULL DEFAULT TRUE,
  PRIMARY KEY (`id`),
  INDEX (`subcategory_id` ASC) VISIBLE,
  INDEX (`tax_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_products_subcategories`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `jardinerie_db`.`subcategories` (`id`),
  CONSTRAINT `fk_products_taxes`
    FOREIGN KEY (`tax_id`)
    REFERENCES `jardinerie_db`.`taxes` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`plants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`plants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `common_name` VARCHAR(255) NULL DEFAULT NULL,
  `latin_name` VARCHAR(255) NULL DEFAULT NULL,
  `genus` VARCHAR(100) NULL DEFAULT NULL,
  `species` VARCHAR(100) NULL DEFAULT NULL,
  `sun_exposure` ENUM('Sun', 'Partial Shade', 'Shade') NULL DEFAULT NULL,
  `water_requirement` ENUM('Low', 'Medium', 'High') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_plants_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `jardinerie_db`.`products` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`criteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`criteria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`plant_criterion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`plant_criterion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plant_id` INT NOT NULL,
  `criterion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`plant_id` ASC, `criterion_id` ASC) VISIBLE,
  INDEX (`plant_id` ASC) VISIBLE,
  INDEX (`criterion_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_plant_criterion_plants`
    FOREIGN KEY (`plant_id`)
    REFERENCES `jardinerie_db`.`plants` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_plant_criterion_criteria`
    FOREIGN KEY (`criterion_id`)
    REFERENCES `jardinerie_db`.`criteria` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`stock_movements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`stock_movements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `movement_type` ENUM('restock', 'sale', 'inventory', 'loss') NOT NULL,
  `movement_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_stock_movements_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `jardinerie_db`.`products` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_carts_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `jardinerie_db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`cart_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`cart_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cart_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`cart_id` ASC, `product_id` ASC) VISIBLE,
  INDEX (`cart_id` ASC) VISIBLE,
  INDEX (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_items_carts`
    FOREIGN KEY (`cart_id`)
    REFERENCES `jardinerie_db`.`carts` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_cart_items_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `jardinerie_db`.`products` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`payment_methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`payment_methods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `logo_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`delivery_methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`delivery_methods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `base_cost_tax_incl` DECIMAL(10,2) NOT NULL,
  `free_shipping_threshold_tax_incl` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `payment_method_id` INT NOT NULL,
  `delivery_method_id` INT NOT NULL,
  `billing_address_id` INT NULL DEFAULT NULL,
  `shipping_address_id` INT NULL DEFAULT NULL,
  `billing_address_text` TEXT NOT NULL,
  `shipping_address_text` TEXT NOT NULL,
  `order_reference` VARCHAR(50) NOT NULL,
  `order_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `total_amount_tax_incl` DECIMAL(10,2) NOT NULL,
  `shipping_cost_tax_incl` DECIMAL(10,2) NOT NULL,
  `status` ENUM('pending', 'paid', 'shipped', 'delivered', 'cancelled') NULL DEFAULT 'pending',
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`order_reference` ASC) VISIBLE,
  INDEX (`user_id` ASC) VISIBLE,
  INDEX (`payment_method_id` ASC) VISIBLE,
  INDEX (`delivery_method_id` ASC) VISIBLE,
  INDEX (`billing_address_id` ASC) VISIBLE,
  INDEX (`shipping_address_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `jardinerie_db`.`users` (`id`),
  CONSTRAINT `fk_orders_payment_methods`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `jardinerie_db`.`payment_methods` (`id`),
  CONSTRAINT `fk_orders_delivery_methods`
    FOREIGN KEY (`delivery_method_id`)
    REFERENCES `jardinerie_db`.`delivery_methods` (`id`),
  CONSTRAINT `fk_orders_billing_address`
    FOREIGN KEY (`billing_address_id`)
    REFERENCES `jardinerie_db`.`addresses` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_orders_shipping_address`
    FOREIGN KEY (`shipping_address_id`)
    REFERENCES `jardinerie_db`.`addresses` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`order_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `unit_price_tax_incl` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`order_id` ASC) VISIBLE,
  INDEX (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `jardinerie_db`.`orders` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_order_items_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `jardinerie_db`.`products` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardinerie_db`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardinerie_db`.`invoices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `invoice_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `total_amount_tax_incl` DECIMAL(10,2) NOT NULL,
  `pdf_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`order_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_invoices_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `jardinerie_db`.`orders` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
